markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "tables", "superscript"]
highlighter: pygments

exclude: ["README.md", "Dockerfile", "CNAME"]
